# Generated by Django 4.2.7 on 2025-10-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_khach_hang', models.CharField(max_length=50, unique=True)),
                ('ten_khach_hang', models.CharField(max_length=200)),
                ('dia_chi', models.TextField()),
                ('dien_thoai', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Khách hàng',
                'verbose_name_plural': 'Khách hàng',
            },
        ),
        migrations.CreateModel(
            name='NhaCungCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_nha_cung_cap', models.CharField(max_length=50, unique=True)),
                ('ten_nha_cung_cap', models.CharField(max_length=200)),
                ('dia_chi', models.TextField()),
                ('dien_thoai', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nhà cung cấp',
                'verbose_name_plural': 'Nhà cung cấp',
            },
        ),
    ]
