# Generated by Django 5.2.7 on 2025-11-11 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_xuatkho_khach_hang'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KhachHang',
        ),
    ]
