# Generated by Django 5.2.7 on 2025-11-11 14:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        ('products', '0002_donvitinh_trang_thai'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_kho', models.CharField(max_length=20, unique=True, verbose_name='Mã kho')),
                ('ten_kho', models.CharField(max_length=100, verbose_name='Tên kho')),
                ('dia_chi', models.TextField(verbose_name='Địa chỉ')),
                ('dien_thoai', models.CharField(blank=True, max_length=15, verbose_name='Điện thoại')),
                ('trang_thai', models.CharField(choices=[('dang_hoat_dong', 'Đang hoạt động'), ('ngung_hoat_dong', 'Ngừng hoạt động'), ('bao_tri', 'Bảo trì')], default='dang_hoat_dong', max_length=20, verbose_name='Trạng thái')),
                ('ghi_chu', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('nguoi_quan_ly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người quản lý')),
            ],
            options={
                'verbose_name': 'Kho',
                'verbose_name_plural': 'Kho',
            },
        ),
        migrations.CreateModel(
            name='KiemKe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_kiem_ke', models.CharField(max_length=50, unique=True, verbose_name='Mã kiểm kê')),
                ('ten_dot_kiem_ke', models.CharField(max_length=200, verbose_name='Tên đợt kiểm kê')),
                ('ngay_kiem_ke', models.DateTimeField(verbose_name='Ngày kiểm kê')),
                ('kho', models.CharField(max_length=100, verbose_name='Kho kiểm kê')),
                ('trang_thai', models.CharField(choices=[('cho', 'Chờ'), ('dang_kiem_ke', 'Đang kiểm kê'), ('hoan_thanh', 'Hoàn thành'), ('huy', 'Hủy')], default='cho', max_length=20, verbose_name='Trạng thái')),
                ('mo_ta', models.TextField(blank=True, verbose_name='Mô tả')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('nguoi_phu_trach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người phụ trách')),
            ],
            options={
                'verbose_name': 'Kiểm kê',
                'verbose_name_plural': 'Kiểm kê',
            },
        ),
        migrations.CreateModel(
            name='ChiTietKiemKe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong_he_thong', models.IntegerField(verbose_name='Số lượng hệ thống')),
                ('so_luong_thuc_te', models.IntegerField(verbose_name='Số lượng thực tế')),
                ('chenh_lech', models.IntegerField(default=0, verbose_name='Chênh lệch')),
                ('ghi_chu', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.sanpham', verbose_name='Sản phẩm')),
                ('kiem_ke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='inventory.kiemke', verbose_name='Đợt kiểm kê')),
            ],
            options={
                'verbose_name': 'Chi tiết kiểm kê',
                'verbose_name_plural': 'Chi tiết kiểm kê',
            },
        ),
        migrations.CreateModel(
            name='NhapKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_phieu', models.CharField(max_length=50, unique=True)),
                ('ngay_nhap', models.DateTimeField(auto_now_add=True)),
                ('tong_tien', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('kho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.kho')),
                ('nguoi_lap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nha_cung_cap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.nhacungcap')),
            ],
            options={
                'verbose_name': 'Phiếu nhập kho',
                'verbose_name_plural': 'Phiếu nhập kho',
                'ordering': ['-ngay_nhap'],
            },
        ),
        migrations.CreateModel(
            name='ChiTietNhapKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('don_gia', models.DecimalField(decimal_places=2, max_digits=15)),
                ('thanh_tien', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.sanpham')),
                ('phieu_nhap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet_nhap', to='inventory.nhapkho')),
            ],
            options={
                'verbose_name': 'Chi tiết nhập kho',
                'verbose_name_plural': 'Chi tiết nhập kho',
            },
        ),
        migrations.CreateModel(
            name='XuatKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_phieu', models.CharField(max_length=50, unique=True)),
                ('ngay_xuat', models.DateTimeField(auto_now_add=True)),
                ('tong_tien', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.khachhang', verbose_name='Kho Xuất')),
                ('kho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.kho')),
                ('nguoi_lap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phiếu xuất kho',
                'verbose_name_plural': 'Phiếu xuất kho',
            },
        ),
        migrations.CreateModel(
            name='ChiTietXuatKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('don_gia', models.DecimalField(decimal_places=2, max_digits=15)),
                ('thanh_tien', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.sanpham')),
                ('phieu_xuat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet_xuat', to='inventory.xuatkho')),
            ],
            options={
                'verbose_name': 'Chi tiết xuất kho',
                'verbose_name_plural': 'Chi tiết xuất kho',
            },
        ),
        migrations.CreateModel(
            name='TonKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong_ton', models.IntegerField(default=0, verbose_name='Số lượng tồn')),
                ('so_luong_kha_dung', models.IntegerField(default=0, verbose_name='Số lượng khả dụng')),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('kho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.kho', verbose_name='Kho')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.sanpham', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Tồn kho',
                'verbose_name_plural': 'Tồn kho',
                'unique_together': {('kho', 'san_pham')},
            },
        ),
    ]
