# Generated by Django 4.2.7 on 2025-10-21 00:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XuatKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_phieu', models.CharField(max_length=50, unique=True)),
                ('ngay_xuat', models.DateTimeField(auto_now_add=True)),
                ('tong_tien', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.khachhang')),
                ('nguoi_lap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phiếu xuất kho',
                'verbose_name_plural': 'Phiếu xuất kho',
            },
        ),
        migrations.CreateModel(
            name='NhapKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_phieu', models.CharField(max_length=50, unique=True)),
                ('ngay_nhap', models.DateTimeField(auto_now_add=True)),
                ('tong_tien', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('nguoi_lap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nha_cung_cap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.nhacungcap')),
            ],
            options={
                'verbose_name': 'Phiếu nhập kho',
                'verbose_name_plural': 'Phiếu nhập kho',
            },
        ),
        migrations.CreateModel(
            name='ChiTietXuatKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('don_gia', models.DecimalField(decimal_places=2, max_digits=15)),
                ('thanh_tien', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('phieu_xuat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet_xuat', to='inventory.xuatkho')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.sanpham')),
            ],
            options={
                'verbose_name': 'Chi tiết xuất kho',
                'verbose_name_plural': 'Chi tiết xuất kho',
            },
        ),
        migrations.CreateModel(
            name='ChiTietNhapKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('don_gia', models.DecimalField(decimal_places=2, max_digits=15)),
                ('thanh_tien', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('phieu_nhap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet_nhap', to='inventory.nhapkho')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.sanpham')),
            ],
            options={
                'verbose_name': 'Chi tiết nhập kho',
                'verbose_name_plural': 'Chi tiết nhập kho',
            },
        ),
    ]
