# Generated by Django 5.2.7 on 2025-11-11 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xuatkho',
            name='khach_hang',
        ),
    ]
