# Generated by Django 5.2.7 on 2025-11-10 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nhapkho',
            options={'ordering': ['-ngay_nhap'], 'verbose_name': 'Phiếu nhập kho', 'verbose_name_plural': 'Phiếu nhập kho'},
        ),
        migrations.CreateModel(
            name='KiemKe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_kiem_ke', models.CharField(max_length=50, unique=True, verbose_name='Mã kiểm kê')),
                ('ten_dot_kiem_ke', models.CharField(max_length=200, verbose_name='Tên đợt kiểm kê')),
                ('ngay_kiem_ke', models.DateTimeField(verbose_name='Ngày kiểm kê')),
                ('kho', models.CharField(max_length=100, verbose_name='Kho kiểm kê')),
                ('trang_thai', models.CharField(choices=[('cho', 'Chờ'), ('dang_kiem_ke', 'Đang kiểm kê'), ('hoan_thanh', 'Hoàn thành'), ('huy', 'Hủy')], default='cho', max_length=20, verbose_name='Trạng thái')),
                ('mo_ta', models.TextField(blank=True, verbose_name='Mô tả')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('nguoi_phu_trach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người phụ trách')),
            ],
            options={
                'verbose_name': 'Kiểm kê',
                'verbose_name_plural': 'Kiểm kê',
            },
        ),
        migrations.CreateModel(
            name='ChiTietKiemKe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong_he_thong', models.IntegerField(verbose_name='Số lượng hệ thống')),
                ('so_luong_thuc_te', models.IntegerField(verbose_name='Số lượng thực tế')),
                ('chenh_lech', models.IntegerField(default=0, verbose_name='Chênh lệch')),
                ('ghi_chu', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.sanpham', verbose_name='Sản phẩm')),
                ('kiem_ke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='inventory.kiemke', verbose_name='Đợt kiểm kê')),
            ],
            options={
                'verbose_name': 'Chi tiết kiểm kê',
                'verbose_name_plural': 'Chi tiết kiểm kê',
            },
        ),
    ]
