# Generated by Django 5.2.7 on 2025-11-12 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_xuatkho_khach_hang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kiemke',
            name='kho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.kho'),
        ),
    ]
