# Generated by Django 5.2.7 on 2025-11-13 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_kiemke_kho'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhapkho',
            name='trang_thai',
            field=models.CharField(default='chưa duyệt', max_length=20),
        ),
    ]
