# Generated by Django 5.2.7 on 2025-11-13 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_nhapkho_trang_thai'),
    ]

    operations = [
        migrations.AddField(
            model_name='xuatkho',
            name='kho_nhan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='phieu_nhan_kho', to='inventory.kho'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='xuatkho',
            name='kho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phieu_xuat_kho', to='inventory.kho'),
        ),
    ]
