# Generated by Django 5.2.7 on 2025-11-11 15:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CongNoNhaCungCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_cong_no', models.CharField(choices=[('nhap_hang', 'Nợ nhập hàng'), ('thanh_toan', 'Thanh toán')], max_length=20)),
                ('so_tien', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('so_tien_con_lai', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('han_thanh_toan', models.DateField()),
                ('trang_thai', models.CharField(choices=[('dang_no', 'Đang nợ'), ('thanh_toan_mot_phan', 'Thanh toán một phần'), ('da_thanh_toan', 'Đã thanh toán'), ('qua_han', 'Quá hạn')], default='dang_no', max_length=20)),
                ('ghi_chu', models.TextField(blank=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('nha_cung_cap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.nhacungcap')),
                ('phieu_nhap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.nhapkho')),
            ],
            options={
                'verbose_name': 'Công nợ nhà cung cấp',
                'verbose_name_plural': 'Công nợ nhà cung cấp',
                'ordering': ['-han_thanh_toan'],
            },
        ),
        migrations.CreateModel(
            name='LichSuThanhToan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_tien_thanh_toan', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('ngay_thanh_toan', models.DateField()),
                ('ghi_chu', models.TextField(blank=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('cong_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_thanh_toan', to='debt.congnonhacungcap')),
            ],
            options={
                'verbose_name': 'Lịch sử thanh toán',
                'verbose_name_plural': 'Lịch sử thanh toán',
                'ordering': ['-ngay_thanh_toan'],
            },
        ),
    ]
