# Generated by Django 5.2.7 on 2025-11-12 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0001_initial'),
        ('partners', '0002_delete_khachhang'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lichsuthanhtoan',
            options={},
        ),
        migrations.RemoveField(
            model_name='lichsuthanhtoan',
            name='ghi_chu',
        ),
        migrations.RemoveField(
            model_name='lichsuthanhtoan',
            name='ngay_tao',
        ),
        migrations.RemoveField(
            model_name='lichsuthanhtoan',
            name='so_tien_thanh_toan',
        ),
        migrations.AddField(
            model_name='lichsuthanhtoan',
            name='nguoi_thanh_toan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lichsuthanhtoan',
            name='so_tien',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='lichsuthanhtoan',
            name='ngay_thanh_toan',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='CongNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_cong_no', models.CharField(max_length=20, unique=True)),
                ('loai_cong_no', models.CharField(choices=[('phai_thu', 'Phải thu'), ('phai_tra', 'Phải trả')], max_length=10)),
                ('ten_hang_hoa', models.CharField(max_length=255)),
                ('so_luong', models.IntegerField(default=1)),
                ('don_gia', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('so_tien', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('so_tien_con_lai', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('nha_cung_cap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.nhacungcap')),
            ],
        ),
        migrations.AlterField(
            model_name='lichsuthanhtoan',
            name='cong_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_thanh_toan', to='debt.congno'),
        ),
        migrations.DeleteModel(
            name='CongNoNhaCungCap',
        ),
    ]
