# Generated by Django 4.2.7 on 2025-10-21 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMucSanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_danh_muc', models.CharField(max_length=100)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('trang_thai', models.BooleanField(default=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Danh mục sản phẩm',
                'verbose_name_plural': 'Danh mục sản phẩm',
            },
        ),
        migrations.CreateModel(
            name='DonViTinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_don_vi', models.CharField(max_length=50)),
                ('mo_ta', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Đơn vị tính',
                'verbose_name_plural': 'Đơn vị tính',
            },
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_san_pham', models.CharField(max_length=50, unique=True)),
                ('ten_san_pham', models.CharField(max_length=200)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('ton_kho', models.IntegerField(default=0)),
                ('gia_nhap', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gia_ban', models.DecimalField(decimal_places=2, max_digits=15)),
                ('trang_thai', models.BooleanField(default=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('danh_muc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.danhmucsanpham')),
                ('don_vi_tinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.donvitinh')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
            },
        ),
    ]
