# Generated by Django 5.2.7 on 2025-11-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donvitinh',
            name='trang_thai',
            field=models.BooleanField(default=True),
        ),
    ]
