# Generated by Django 5.2.7 on 2025-11-12 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_donvitinh_trang_thai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanpham',
            name='ton_kho',
        ),
    ]
